name: Build the .deb package

# Trigger the workflow whenever you push new .deb files or change the workflow itself
on:
  push:
    paths:
      - '**'
jobs:
  build:
    permissions:
      contents: read
      packages: write
      release: write
    runs-on: ubuntu-latest

    # 1. Dowload the script
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: build 

      # 2. Execute the build script
      - name: execute build script
        run: |
          cd build
          chmod +x build.sh
          ./build.sh

      # 3. Upload everything in the built directory to the relases
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.version }}
          artifacts: "built/*.deb"
          body: "This is the release of the latest build of A Neuro Who Can't Sing. It is completely automated and isnt tested, so good luck!"
